---

- name: Install Apache on Ubuntu
  hosts: your_target_server
  become: yes
  vars:
    - service_name: apache2
  
  tasks:
    - name: Install Apache
      apt:
        name: "{{ service_name }}"
        state: present

    - name: Start Apache service
      service:
        name: "{{ service_name }}"
        state: started