---

- name: copy module
  hosts: localhost

  tasks:
  - name: copy files
    copy:
      src: /etc/temp/file.txt
      dest: /mnt/e
      owner: paul
      group: paul
      mode: 0777  # ugo=rw
      backup: true