---

- name: file module
  hosts: localhost

  tasks:
  - name: Create a file
    file:
      path: /tmp/new.txt
      state: touch   # other states "absent" - to delete
      owner: soub
      group: soub
      mode: u=rwx,g=rw,o=r
      
  - name: Crate a Directory
    file:
      path: /tmp/myfolder
      state: directory
