---

- name: Find and Stop Processes on Remote server
  hosts: localhost
  become: true

  tasks:
  - name: Kill process
    ignore_errors: yes
    shell: "pgrep nginx | xargs kill"
  
  - name: start a service
    service:
      name: nginx
      state: started
