---

- name: user task
  hosts: localhost
  become: true
  tasks:
      - name: Create Admin User
        user: name=admin state=present uid=5001
      
      - name: Delete user dojo
        user: name=dojo state=absent
      
      - name: Install Tree
        apt: name=tree state=present
      
      - name: Install ntp
        apt: name=ntp state=presentQ1