---

- name: Install httpd
  become: true
  apt:
    name: "{{ httpd_packgae_name }}"
    state: present

- name: place custom HTML file
  become: true
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: start service
  become: true
  service:
    name: "{{ httpd_packgae_name }}"
    state: started
    enabled: yes